name: Docs Deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Checkout dev
        uses: actions/checkout@v4
        with:
          ref: dev
          path: devbranch
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.12.0"
          python-version: "3.14"
          enable-cache: true
      - name: Install dependencies
        run: uv sync --frozen --group docs
      - name: Git setup and update
        run: |
          git config user.name "GitHub Action" && git config user.email "github-action@github.com"
          git fetch origin
      - name: Build Docs for main
        run: uv run --frozen mkdocs build
      - name: Build Docs for dev
        run: |
          cd devbranch
          uv run --project .. --frozen mkdocs build
          mv site dev
          cd ..
          mv devbranch/dev site/
      - name: Add latest web build and deploy
        run: |
          uv run --frozen mkdocs gh-deploy --dirty
