# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.12.0"
        python-version: "3.14"
        enable-cache: true
    - name: Build and publish
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_HANDWRITE }}
      run: |
        uv build
        uv publish
