name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - name: Checkout full upstream repo
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install fontforge
        run: |
          sudo apt install software-properties-common
          sudo apt -y update
          sudo apt-get install libjpeg-dev libtiff5-dev libpng-dev libfreetype6-dev libgif-dev libgtk-3-dev libxml2-dev libpango1.0-dev libcairo2-dev libspiro-dev libuninameslist-dev python3-dev ninja-build cmake build-essential gettext;
          git clone https://github.com/fontforge/fontforge
          cd fontforge
          mkdir build
          cd build
          cmake -GNinja ..
          ninja
          ninja install
      - name: Install Potrace
        run: |
          sudo apt install -y potrace
      - name: Install Handwrite
        run: |
          pip install -e .
      - name: Test
        run: |
          python setup.py test
